# Site settings
title: Shyama Sastha Krishnamoorthy Srinivasan
email: shyamas@iiitd.ac.in
description: > # this means to ignore newlines until "baseurl:"
   Graduate researcher at IIIT-Delhi. Interested in leveraging HCAI/AL/ML tools and technologies for affective computing, especially in the domains of accessibility, sustainability, and IoT.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.shyamsastha.github.io" # the base hostname & protocol for your site
production_url: "https://www.shyamsastha.github.io"
github_username: shyamasastha
permalink: /blog/:year/:month/:title.html

twitter:
  username: SasthaShyama

sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
